apiVersion: apps/v1
kind: Deployment
metadata:
  name: mavenpfcti-app
  labels:
    app: mavenpfcti-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mavenpfcti-app
  template:
    metadata:
      labels:
        app: mavenpfcti-app
    spec:
      containers:
      - name: mavenpfcti
        image: miguelcampos7/mavenpfcti
#        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: mavenpfcti-svc
spec:
  selector:
    app: mavenpfcti-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
      name: http